# Use a imagem base do Nginx
FROM nginx:latest

# Copiar o arquivo de configuração do Nginx para o contêiner
COPY default.conf /etc/nginx/conf.d/default.conf

# Expor a porta 80 para o Nginx
EXPOSE 80
