version: '3.9'
services:
  nginx:
    build:
      context: ./dockerfiles/nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./dockerfiles/php
    ports:
      - "81:81"
    volumes:
      - .:/var/www/html/
